# Generated by Django 4.2.19 on 2026-06-26 15:25

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('professor', 'Professor'), ('student', 'Student')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'ordering': ['name', 'email'],
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('invite_code', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'ordering': ['grade', 'section', 'subject', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lectures/%Y/%m/')),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('original_transcript', models.TextField(blank=True, null=True)),
                ('whiteboard_notes', models.TextField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Video Uploaded'), ('transcribing', 'Transcribing Audio'), ('translating', 'Translating Transcript'), ('summarizing', 'Generating Summary'), ('graphing', 'Building Knowledge Graph'), ('generating_quiz', 'Generating Quiz Questions'), ('completed', 'Processing Complete'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='api.classroom')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.classroom')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.lecture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('vector_store_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('score', models.FloatField()),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_count', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.quiz')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.IntegerField()),
                ('explanation', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_details', to='api.studentquizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='api.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('supported_languages', models.JSONField(default=api.models.default_supported_languages)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='api_organiz_slug_a5480a_idx')],
            },
        ),
        migrations.CreateModel(
            name='LectureTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('pdf_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.lecture')),
            ],
            options={
                'ordering': ['language_code'],
            },
        ),
        migrations.CreateModel(
            name='LectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_seconds', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='api.lecture')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph', to='api.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.classroom')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.organization'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_teaching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classrooms_enrolled', through='api.ClassroomEnrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['student', 'quiz'], name='api_student_student_3aaf7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentquizattempt',
            unique_together={('student', 'quiz')},
        ),
        migrations.AlterUniqueTogether(
            name='quizattemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['lecture'], name='api_quiz_lecture_6f8c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['classroom', 'is_published'], name='api_quiz_classro_f6c949_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturetranslation',
            index=models.Index(fields=['lecture', 'language_code'], name='api_lecture_lecture_611ca0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturetranslation',
            unique_together={('lecture', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='lectureprogress',
            index=models.Index(fields=['student', 'lecture'], name='api_lecture_student_8dc1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureprogress',
            index=models.Index(fields=['lecture', 'last_accessed_at'], name='api_lecture_lecture_d73b91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together={('student', 'lecture')},
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['classroom', 'processing_status'], name='api_lecture_classro_b6349e_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['processing_status'], name='api_lecture_process_92653c_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomenrollment',
            index=models.Index(fields=['user', 'classroom'], name='api_classro_user_id_ccca24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomenrollment',
            unique_together={('user', 'classroom')},
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['invite_code'], name='api_classro_invite__223bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['professor'], name='api_classro_profess_e0e08b_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['organization'], name='api_classro_organiz_5913a9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='api_user_email_a7eefd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='api_user_role_9b9076_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='api_user_organiz_061dcf_idx'),
        ),
    ]
