# Generated by Django 5.2.15 on 2026-06-27 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lecturepipelinerun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='syllabus/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'TXT')], max_length=10)),
                ('extracted_text', models.TextField(blank=True)),
                ('text_token_count', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='knowledgegraph',
            name='lecture',
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['grade', 'section', 'name']},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Video Uploaded'), ('transcribing', 'Transcribing Audio'), ('translating', 'Translating Transcript'), ('summarizing', 'Generating Summary'), ('flowchart', 'Building Flow Chart'), ('mindmap', 'Building Mind Map'), ('generating_quiz', 'Generating Quiz Questions'), ('completed', 'Processing Complete'), ('failed', 'Processing Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecturepipelinerun',
            name='current_stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('transcribing', 'Transcribing'), ('translating', 'Translating'), ('summarizing', 'Summarizing'), ('flowchart', 'Flowchart'), ('mindmap', 'Mindmap'), ('generating_quiz', 'Generating Quiz'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_board_name_1c926b_idx')],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='api.board'),
        ),
        migrations.CreateModel(
            name='FlowChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mermaid_code', models.TextField()),
                ('node_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_chart', to='api.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('numeric_value', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['numeric_value', 'name'],
                'indexes': [models.Index(fields=['numeric_value'], name='api_grade_numeric_026c33_idx'), models.Index(fields=['name'], name='api_grade_name_3aab42_idx')],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='api.grade'),
        ),
        migrations.CreateModel(
            name='InteractiveVisualizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('generated_code', models.TextField()),
                ('code_type', models.CharField(choices=[('threejs', 'Three.js'), ('p5js', 'p5.js'), ('html_canvas', 'HTML Canvas')], default='html_canvas', max_length=20)),
                ('model_name', models.CharField(default='gpt-5.2-codex', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactive_visualizers', to='api.lecture')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_visualizers', to='api.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_visualizer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mermaid_code', models.TextField()),
                ('node_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mind_map', to='api.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.board')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.grade')),
            ],
            options={
                'ordering': ['board__name', 'grade__numeric_value', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='api.subject'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['subject'], name='api_classro_subject_ecbf3a_idx'),
        ),
        migrations.AddField(
            model_name='syllabusdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_documents', to='api.organization'),
        ),
        migrations.AddField(
            model_name='syllabusdocument',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_documents', to='api.subject'),
        ),
        migrations.AddField(
            model_name='syllabusdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_syllabus_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='KnowledgeGraph',
        ),
        migrations.AddIndex(
            model_name='interactivevisualizer',
            index=models.Index(fields=['organization', 'created_at'], name='api_interac_organiz_c7bdda_idx'),
        ),
        migrations.AddIndex(
            model_name='interactivevisualizer',
            index=models.Index(fields=['requested_by', 'created_at'], name='api_interac_request_3155dd_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['board', 'grade'], name='api_subject_board_i_82fdfc_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='api_subject_name_ad1571_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('board', 'grade', 'name')},
        ),
        migrations.AddIndex(
            model_name='syllabusdocument',
            index=models.Index(fields=['organization', 'subject'], name='api_syllabu_organiz_699d23_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabusdocument',
            index=models.Index(fields=['processing_status'], name='api_syllabu_process_49bdbc_idx'),
        ),
    ]
