# Generated by Django 5.2.15 on 2026-06-28 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_syllabusdocument_remove_knowledgegraph_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_as_class_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClassroomSubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_assignments', to='api.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_assignments', to='api.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject__name'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='subject_teachers',
            field=models.ManyToManyField(related_name='classrooms_as_subject_teacher', through='api.ClassroomSubjectTeacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('verify', 'Email Verification'), ('reset', 'Password Reset')], max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used'], name='api_otpveri_email_d9f9fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('student_identifier', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapped_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapped_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_emails', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_emails', to='api.organization')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='classroomsubjectteacher',
            index=models.Index(fields=['classroom', 'subject'], name='api_classro_classro_ebb3ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomsubjectteacher',
            unique_together={('classroom', 'teacher', 'subject')},
        ),
        migrations.AddIndex(
            model_name='whitelistedemail',
            index=models.Index(fields=['organization', 'is_used'], name='api_whiteli_organiz_edb6c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whitelistedemail',
            unique_together={('email', 'organization')},
        ),
    ]
